# Tests that folding still occurs if a runtime error would be thrown
var x = func() {};
x+1+(2*3);
